name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python ${{ matrix.python-version }} on {Linux, MacOS}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
      if: runner.os != 'Windows'
    - name: Set up Python ${{ matrix.python-version }} on Windows
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      if: runner.os == 'Windows'
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest tests/
